project:
  type: website

website:
  title: "Twirly Bird"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Blog
        href: blog.qmd
      - text: Contact
        href: contact.qmd
  page-footer:
    center: "&copy; 2025 Twirly Bird"

format:
  html:
    theme: cosmo
    toc: true
